apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
        - name: hotels
          image: solas98/hotel-service
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "10m"
          ports:
            - name: http
              containerPort: 3002
              protocol: TCP