apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: solas98/user-service
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP