apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - name: reservations
          image: solas98/reservation-service
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "10m"
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP