apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - name: reservations
          image: solas98/reservation-service
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP